### ISSUE TITLE
Module errors

### ISSUE THREAD

**Issue by CirnoOMFG** [N4GR/Fortnite-Festival-AFK-XP#2]
Everytime I try to run the main.py (I have everything installed) it says "No module named cv2" it also does this with several other modules.

**Comment by CirnoOMFG** [comment]
I fixed that, but not it says "numpy not available"

**Comment by N4GR** [comment]
Hey, please read the pre-requirements in the future.
Run the following command in terminal from the base directory:
`pip install -r "requirements.txt"`
