### ISSUE TITLE
Even after running pip install -r "requirements.txt" i still get ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by thatonecookie** [N4GR/Fortnite-Festival-AFK-XP#3]
Not sure what im doing wrong i double checked my python versions and everything and im not sure if this means anything but lego fortnite script works fine

**Comment by N4GR** [comment]
Hello, please replace requirements.txt with:

```
easyocr==1.7.1
opencv_python==4.10.0.84
opencv_python_headless==4.10.0.84
psutil==5.9.8
PyAutoGUI==0.9.54
screeninfo==0.8.1
tqdm==4.66.2
```

**Comment by thatonecookie** [comment]
Im still having issues after replacing them heres the error now 
![image](https://github.com/user-attachments/assets/fe0f3851-c6ee-4fb8-8347-44592314d88d)
